### ISSUE TITLE
Model design issue

### ISSUE THREAD

**Issue by fushh** [MCG-NJU/AdaMixer#1]
Thanks for your great works!

I have a question about the design of positional vector (x, y, z, r). In most of DETR-like detectors, the positional vector are learnable, such as DAB-DETR, Anchor-DETR. In your design, you detach it from computation graph. Dose learnable positional vector hurt the performance?

**Comment by sebgao** [comment]
Thanks for your interest to our work!

In the initial experiments on building AdaMixer, the learnable or fixed positional vector has very similar performances. We are in favor of the latter form for its simplicity.
