### ISSUE TITLE
work_dirs files

### ISSUE THREAD

**Issue by sanmulab** [MCG-NJU/AdaMixer#11]
Hello author! When I'm training, work_dirs will generate all the configs and mmdet files, is this necessary? If it is not necessary, how can I turn off this setting?

**Comment by sebgao** [comment]
You can comment off https://github.com/MCG-NJU/AdaMixer/blob/50223e02465758d5c8a81674f8b5cdefcb99dcf2/tools/train.py#L152-L162 to turn off this settings.

**Comment by sanmulab** [comment]
OK, thank you!
