### ISSUE TITLE
RuntimeError: output with shape [16, 300, 300] doesn't match the broadcast shape [1, 16, 300, 300]

### ISSUE THREAD

**Issue by sanmulab** [MCG-NJU/AdaMixer#12]
I don't know if it is a problem with my environment, I just changed the dataset path to my own, but the error is reported. My torch==1.3.1.
error:
  File "/home/ubuntu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 3352, in multi_head_attention_forward attn_output_weights += attn_mask
RuntimeError: output with shape [16, 300, 300] doesn't match the broadcast shape [1, 16, 300, 300]

**Comment by sebgao** [comment]
What is your MMCV version? You can view it by `pip show mmcv` or `pip show mmcv-full`.

**Comment by sebgao** [comment]
By the way, we recommend to install `pytorch>=1.5`

**Comment by sanmulab** [comment]
Thanks! Problem solved, I used the new environment for training.

**Comment by sanmulab** [comment]
Test problem: When the model starts to evaluate, an error is reported: **AttributeError: 'InitialQueryGenerator' object has no attribute 'aug_test_rpn'.** Why is this? The default test configuration I use: test_cfg=dict(rpn=None, rcnn=dict(max_per_img=300)

**Comment by sebgao** [comment]
Sorry, multi-scale testing is not currently supported by AdaMixer. Please use the single scale testing data loading protocol.
