### ISSUE TITLE
Excuse me, does COCO minival mean coco as a whole dataset or as part of it?

### ISSUE THREAD

**Issue by fadaishaitaiyang** [MCG-NJU/AdaMixer#16]
This is important to me and thank you very much for your answer！

**Comment by sebgao** [comment]
Thank you for your interest in our work, you can refer to the paragraph __Dataset__ in the section __Implementation Details__.

![474531655300334_ pic](https://user-images.githubusercontent.com/26200605/173841700-65c4c67d-e8e3-4567-81f9-ae94dccbeb1e.jpg)
