### ISSUE TITLE
[BUG] params M's dimention shape mismatch

### ISSUE THREAD

**Issue by Shiyang980713** [MCG-NJU/AdaMixer#17]
In the code 'mmdet/models/roi_heads/bbox_heads/adaptive_mixing_operator.py'
[line69] self.m_parameters = self.eff_in_dim * self.eff_out_dim
[line116-117] M, S = params.split([self.m_parameters, self.s_parameters], 2)
M got a dim [..., self.eff_in_dim * self.eff_out_dim].

However, M is reshaped to [..., self.eff_in_dim, self.eff_in_dim] in 
[line140-141] M = M.reshape(B*N, G, self.eff_in_dim, self.eff_in_dim)

Is that a bug or feature?

**Comment by sebgao** [comment]
Hi,

Thank you for your interest in our work and code. Actually this is a bug but does not have actual effects on the current AdaMixer setup since `eff_in_dim` = `eff_out_dim` in the current implementation. I'll fix it.
