### ISSUE TITLE
Why cannot I find Adamixer in  the mmdetection?

### ISSUE THREAD

**Issue by Ys-PUAL** [MCG-NJU/AdaMixer#23]
Thanks for your work!! but I cannot find the Adamixer... 

![image](https://user-images.githubusercontent.com/89328339/201859882-9b5c3b59-bc56-4cb0-955b-7719ad7ac28e.png)
Is my mmdetetion version wrong? (mmdet=2.25.3 and mmcv-full=1.7.0)

**Comment by sebgao** [comment]
Ooops, you should git clone _this_ repo rather than the official mmdetection repo as our code has not yet been integrated into the official mmdetection repo now.

**Comment by Ys-PUAL** [comment]
Thanks!!!!
