### ISSUE TITLE
What is the function of  the weight for the j-th feature map wj

### ISSUE THREAD

**Issue by ZiMo-Chen** [MCG-NJU/AdaMixer#3]
What is the function of  the weight for the j-th feature map wj

**Comment by sebgao** [comment]
It's in
https://github.com/MCG-NJU/AdaMixer/blob/16ec13d8a941707667165800c002fe51292a0a50/mmdet/models/roi_heads/bbox_heads/sampling_3d_operator.py#L48

And it is called in
https://github.com/MCG-NJU/AdaMixer/blob/16ec13d8a941707667165800c002fe51292a0a50/mmdet/models/roi_heads/bbox_heads/sampling_3d_operator.py#L88
