### ISSUE TITLE
Is adamixer suitable for cascade-mask-rcnn?

### ISSUE THREAD

**Issue by Senwang98** [MCG-NJU/AdaMixer#7]
Hi, 
Thanks for your work, I am doing some work to improve detection performance.
I wonder if adamixer suitable for cascade-mask-rcnn?
Wishing for your reply.

**Comment by sebgao** [comment]
Assuming that you need AdaMixer to perform instance segmentation, the answer is absolutely yes when equipping AdaMixer with an extra mask prediction branch (in fact, we're currently conducting relevant experiments). Besides, there are some researches [1, 2] on how to perform instance with query-based detectors.

[1] SOLQ: Segmenting Objects by Learning Queries
[2] Instances as Queries
