### ISSUE TITLE
Visualization about sampling points

### ISSUE THREAD

**Issue by qiumeng6** [MCG-NJU/AdaMixer#8]
Thanks for your work!
The visualization of sampling points for object is very cool.
Are there any code about it in the project?     +.  .+
                                                                        0

**Comment by sebgao** [comment]
Dumping sampling points is already in the project:
https://github.com/MCG-NJU/AdaMixer/blob/910f9900ce78236c53e03bfb9323b09d45a5da2c/mmdet/models/roi_heads/bbox_heads/adamixer_decoder_stage.py#L141

The code to visualize them is not available now. I will reorganize relevant codes and provide a jupyter notebook in a few days.

**Comment by qiumeng6** [comment]
OK!!
Thanks for your reply.

> Dumping sampling points is already in the project:
> 
> https://github.com/MCG-NJU/AdaMixer/blob/910f9900ce78236c53e03bfb9323b09d45a5da2c/mmdet/models/roi_heads/bbox_heads/adamixer_decoder_stage.py#L141
> 
> The code to visualize them is not available now. I will reorganize relevant codes and provide a jupyter notebook in a few days.

OK!!
Thanks for your reply.

**Comment by sebgao** [comment]
We have added the jupyter notebook https://github.com/MCG-NJU/AdaMixer/blob/main/visualize_sampling_points.ipynb
