### ISSUE TITLE
About the "debug" and "postfix" in config file

### ISSUE THREAD

**Issue by Xuyihaoby** [MCG-NJU/AdaMixer#9]
Thank you for your inspiring work!
I was wondering the function of 'debug' and 'postfix' in the config file.

**Comment by sebgao** [comment]
Thank you for your interest in our work.
The `debug` in the config file is just deprecated and you can ignore it. The `postfix` is the postfix of the working experiment dir, helping distinguishing several experiments of the same config, like `0412_0014` in `work_dirs/adamixer_mmdet/adamixer_r50_1x_coco_0412_0014`.

**Comment by Xuyihaoby** [comment]
Got it！Thank you！
